version: "3"
services:
  # Mongodb - Database
  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo-data-volume:/data/db

  # Mysql - Database
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: aaa

  # Phpmyadmin - Mysql UI
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8090:80
    volumes:
      - /sessions

volumes:
  mongo-data-volume:
